version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package_1.zip .
      - zip -r9 ../deployment_package_2.zip .
      - cd ..
      # - cd Lambdas
      - mv s3-search.py lambda_function.py
      - zip -g deployment_package_1.zip lambda_function.py
      - mv lambda_function.py s3-search.py
      - mv s3-upload.py lambda_function.py
      - zip -g deployment_package_2.zip lambda_function.py
      - mv lambda_function.py s3-upload.py

  post_build:
    commands:
      - echo "Updating lambda Functions..."
      - aws lambda update-function-code --function-name s3-search --zip-file fileb://deployment_package_1.zip
      - aws lambda update-function-code --function-name s3-upload --zip-file fileb://deployment_package_2.zip
      - echo "DONE!!"
