AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LF1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: LF1_index_img.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambdas/
  LF2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: LF2_search_photot.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambdas/
